local_app_path: &local_app_path /usr/app
local_artifacts_path: &local_artifacts_path !join [*local_app_path, /artifacts]
local_data_path: !join [*local_artifacts_path, /breast-cancer-wisconsin-data.zip]

target_column: diagnosis
train_size: 0.8
model_type: linear_model.LogisticRegression
n_iterations: 10
model_parameters:
  C:
    uniform: [0.2, 1]
  penalty:
    choice: [l1, l2, elasticnet]